DROP TABLE IF EXISTS PRODUCT;
  
CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(250) NOT NULL,
  product_code VARCHAR(50)	NOT NULL UNIQUE,
  type VARCHAR(50) NOT NULL,
  family VARCHAR(50) NOT NULL
);